spring:
  application:
    name: YouQuiz
  datasource:
    url: jdbc:postgresql://localhost:5432/youquiz
    username: postgres
    password: ahmed
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

